addons:
  apt:
    packages:
    - zsh
services: docker
env:
  global:
  - DOCKER_USER=callforamerica
  # DOCKER_PASS
  - secure: "dhRRoVyDz+C5hBk+qd4rE9nYTGKOq4yVaMhRDVJW24yE5gQWmG/3SP1IDWBI7SogsQOO9g0crhPfBrPU0Cyd60TnZ/nYmUJbNrUq6/PupzMh5tFyoqV+cfSCNAx375i3+JGos5hmQ0XHFtu3NZuOnNBeBQJpt8mI3nyybhts3rKFQQhjlN5QMM1+woaUlnWOKubP0dlcKIbrrMEhG+omZTWD8QzpFQUHEsUss460DhUlYOdzjJ9RcRVGSpdXJUASOsknXqTIu5x5uVs7lvx09kwkyf58Ry93SOKLBG0XG5W/L/B28SrChpRpSDIgMwwebuwEgL7Qd+OSyICOj9xKOI2Hkq2hMQ1tPukoVQPKzu4vtApJMOGxFCcUyesiKwuon8xgw2VN8jbI9EyCGQZ6ddlzH/l6Hxhd/4QCnxWKyVK0HyLTRavuUecbtZATaYLo8VrN3ga4i+riUnmWCbzvY8TbtWHvUSliyJgV7J9iAyxqBvYD6Tr7chDrmNrwxswdAle0URbkwtI7fUnVbJqqLejOfW2C6/vcpAkIn/HrRYiBgsjeVkIQzUmjSkmHg/ndSZ7kzBDDVI5Vf6XEcBVfy3k08nXTNlSQmFowaalAqshcXsrDkLkvR6CgY8GV4THEElXa58azIYRACuFuwOyVvMeYmOch6j7tzpfhzio5+Lk="
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "gCIKaH7zPOXOCuvjTYeGsIVi2s6kjY2Lkw/oNcpqfa/XPypD197Q//DB1o5Vi+tYWf7i6/Wm45aVZy9YNnMROoQYp4sHu+Z8oveGDSRuWnGrgTEU7ipyMeFHont6HH1Kz7JKlgaMSaUm4WjNLfd10FAo6iFd2cXaKHErDRf+AisntLJdw+3/CP1Dpelmx83hqmu32WtzBgxrffdyYO8dw6T0Vk58gmUqibtPPl4LbVlKg1wWZv+GHHv4y0wIDiCaGVCuikuDM91uvs2Vt9mGUPHzNxpIovy0ZNS1/PNz8sdXgmaW+H18aacPwFvFVm/Kx4LG4ZQ9ZgmZmYPucNyUvTJ/xSkchEuadmUnlYM5tM/rofSCHOPeI1AYMu9e8UY1B9i8VnF02NgYrOfPXYJ6vV+fgVQedRjTkvIkGTtXEAPQhG6kdH2CyUE5yhzA03WDPFpoc3fVpv55np1GwSusd62iC0epXlcxEROmRi9fvf9ldM/yR+Dt/fN2zHGXrHabfHMmMfkTUmpY/c0U0laA0hdl80hbjr3XJY8WJGmbKZA3H8jIekC1wCIT0u1IdFHzffDg9ZSBW5DzsQL1buNHESCuSUwS3nctxHtDVW/uaCdz+eHAJsew+xjD9QF7IWWNeNp3JqSu44ILDE0zSmPYIffNv853EG9Fq4smw6VqpdM="
    on_success: always
    on_failure: always

before_install:
- source scripts/ci-env.sh
- make info

install:
- make build
- make launch

script:
- sleep 20
- make test

after_success:
- make tag ALT_TAG=${TRAVIS_COMMIT::6}
- make tag ALT_TAG=travis-$TRAVIS_BUILD_NUMBER
- make hub-login
- make hub-push
- make hub-build
