addons:
  apt:
    packages:
    - realpath
language: python
python:
- "3.6"
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=telephoneorg
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=telephoneorg
  # DOCKER_PASS
  - secure: "E/9xtV7WktRE25s6s+Kxe33tPaget12uIrXOHDgx/C7Hx+YPnWb0T6BtvJCnSbTOFYakQ8jP0rLJo4ABjfziCNBpSYOgIevu7wwWek3iwvPENAigO82x2DXKTU8/zHr59kmjgOyOmB+H64ZqkCSGUWQ8lHNHDvfMu1dgiUnNQeXs3jdj1Zeqwu7TMnlq9AzvZRKNnc7VELves8yH0fi9B7338DaRGhKSnoWh9oL5O8X5ssbk2Bm7jhpmyPNNXedSImD1BkAtvUbpcN2zBlP5kLp1kwWBekXvag3rZYagdszB8uusV9BAEhtK1n7eQR9LoIus2V5fQokgc9T/+Qtypz6l6QGH5IfF7jQ0xbg+Fs6rEm+NKIVrxYVWzuuqGMjYHQnOTrXH7Re4m1uuv0C2EIhl3vvlUV6PJem+1QCoc1D+7ZVtINIBZfVzH5nzK9I3gpOm+2iWPjiQal4m4C8Z85EjZaI3y4CDR3oq9LwrSy+Gn0/JSkOeC3OlbhqanbHut97ctVnuEAurY7jVPphekhdUK2W1+cIhdRO85qqznhSW7AUEK3WeHgWN3oS5gcom4cCR52LZaVmT16h2SKJTh+5jyjnD71Q6A5mciHUCC/1iGp6b476diDSDK81lMX+3AvSI5eMUXrwZy5OiMrPNijsmUEGBx54q78T2w7EkJFk="
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "DxDYLKiVCVS5i2ZE8VLtEajGimC0F8KB8/UMa+DBDmvf8h2MGn7YhiVc3cUeEX66l02SjxygumRTiWBNaqtRCncpL78CQx4W9cRtUSDMCqsVyoluQC1JUfzY2W7XW+WjuD5k7HqlP1u5L0yH4Iuv9aUa9opBaryoGmdSOy1LxCbWZfkbtvI0Yc8reasdYjXZ4TZBslD8T0uLbnBWdj82tfFqvPMoI5lL8BzzH+GxQfkhNx4Owbl4f+5277hrpNohxkv7XB4FVnl/vM0UBu5125gACPy1wqX9PTATdkLnRwt2voaOOR5AYy6SmGnrRe2X5uOqypMa7kXyn2bvT3y6ftNuQDFpDd0LhMeIwMIwcAxDZRigDznFemUPzp/WRBlJrOWEIael2eFM22HwZ6A8PHlgA50l3Oxp8ykD0TJ/n5WUhx9yEotifaZau4B9sAgo76OWTa1sfdnbHhx0mxB0iH5PQtn0nHBcbaCv+uWyPx17qLW5d6iFPg3DJdeLN6oEG1z21vLhxmwI+mDwUDK55sGkFo77bbhul02rVJNOJuvYXuPAvxeebBfDDvLEMjSLo4SoA+e+kyrvbJ3rXneL7sXSF7POwAAvr5s5+URKtF7UpImhxPyIRL/2cAJoP0cn0YZg3caCRHiaSpTz4jluDEb9sncTctny4UbEVwBB7qA="
    on_failure: always

before_install:
- source scripts/ci/environment.sh
- pip install --upgrade docker-compose
- pip install invoke

install: inv dc.build

script: inv test

after_success:
- ci-tag-build
- hub-push
- hub-update-readme
