version: '2.1'
services:
  freeswitch:
    container_name: freeswitch
    hostname: freeswitch.local
    build: .
    image: callforamerica/freeswitch:${TAG:-latest}
    environment:
      FREESWITCH_DISABLE_NAT_DETECTION: 'false'
      FREESWITCH_RTP_START_PORT: 16384
      FREESWITCH_RTP_END_PORT: 16484
      ERLANG_COOKIE: test-cookie
    ports:
    - "11000:10000"
    - "11000:10000/udp"
    - "16384-16484:16384-16484/udp"
    - "8021:8021"
    - "8031:8031"
    networks:
      local:
        aliases:
        - freeswitch.local
    cap_add:
    - IPC_LOCK
    - NET_ADMIN
    - NET_RAW
    - NET_BROADCAST
    - SYS_NICE
    - SYS_RESOURCE
networks:
  local:
