apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: freeswitch
  labels:
    app: freeswitch
    project: valuphone
    environment: production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: freeswitch
        project: valuphone
        environment: production
    spec:
      hostNetwork: true
      # nodeSelector:
      #   kubernetes.io/hostname: saturn.valuphone.com
      containers:
      - name: freeswitch
        image: callforamerica/freeswitch
        imagePullPolicy: Always
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
            - NET_ADMIN
            - NET_RAW
            - NET_BROADCAST
            - SYS_NICE
            - SYS_RESOURCE
        env:
        - name: KUBE_SEARCH_DOMAINS_ADD
          valueFrom:
            configMapKeyRef:
              name: freeswitch
              key: kube.search-domains.add
        - name: ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              name: erlang-cookie
              key: erlang.cookie
        - name: FREESWITCH_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: freeswitch
              key: rabbitmq.log.level
        - name: FREESWITCH_LOG_COLOR
          valueFrom:
            configMapKeyRef:
              name: freeswitch
              key: freeswitch.log.color
        - name: FREESWITCH_RTP_START_PORT
          valueFrom:
            configMapKeyRef:
              name: freeswitch
              key: freeswitch.rtp.start-port
        - name: FREESWITCH_RTP_END_PORT
          valueFrom:
            configMapKeyRef:
              name: freeswitch
              key: freeswitch.rtp.end-port
        - name: FREESWITCH_DISABLE_NAT_DETECTION
          valueFrom:
            configMapKeyRef:
              name: freeswitch
              key: freeswitch.disable-nat-detection
        - name: FREESWITCH_TLS_ENABLE
          valueFrom:
            configMapKeyRef:
              name: freeswitch
              key: freeswitch.tls.enable
        ports:
        - name: event-socket
          containerPort:  8021
        - name: mod-kazoo
          containerPort:  8031
        - name: sip
          protocol: UDP
          containerPort: 11000
        resources:
          requests:
            cpu: 8
            memory: 6Gi
          limits:
            cpu: 8
            memory: 6Gi
        readinessProbe:
          exec:
            command: ["fs_cli", "-x", "status", "|", "grep", "-q", "^UP"]
          initialDelaySeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          exec:
            command: ["fs_cli", "-x", "status", "|", "grep", "-q", "^UP"]
          initialDelaySeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        volumeMounts:
        - name: freeswitch-ramfs
          mountPath: /volumes/freeswitch
      volumes:
      - name: freeswitch-ramfs
        emptyDir:
          medium: Memory
      restartPolicy: Always
