apiVersion: v1
kind: ConfigMap
metadata:
  name: freeswitch
  labels:
    app: freeswitch
    project: valuphone
    environment: production
data:
  kube.search-domains.add: 'true'
  freeswitch.log.level: info
  freeswitch.log.color: 'true'
  freeswitch.rtp.start-port: '16384'
  freeswitch.rtp.end-port: '32768'
  freeswitch.disable-nat-detection: 'false'
  freeswitch.skip-sounds: 'false'
  freeswitch.tls.enable: 'false'
