apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: freeswitch
  labels:
    app: freeswitch
    project: telephoneorg
    environment: production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: freeswitch
        project: telephoneorg
        environment: production
    spec:
      hostNetwork: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: media-server
                operator: In
                values:
                - 'true'
      # nodeSelector:
      #   kubernetes.io/hostname: saturn.telephoneorg.com
      containers:
      - name: freeswitch
        image: telephoneorg/freeswitch:latest
        imagePullPolicy: Always
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
            - NET_ADMIN
            - NET_RAW
            - NET_BROADCAST
            - SYS_NICE
            - SYS_RESOURCE
        env:
        - name: ERLANG_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: freeswitch
              key: erlang.hostname
        - name: ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              name: erlang
              key: erlang.cookie
        - name: FREESWITCH_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: freeswitch
              key: freeswitch.log.level
        - name: FREESWITCH_LOG_COLOR
          valueFrom:
            configMapKeyRef:
              name: freeswitch
              key: freeswitch.log.color
        - name: FREESWITCH_RTP_PORT_RANGE
          valueFrom:
            configMapKeyRef:
              name: freeswitch
              key: freeswitch.rtp.port-range
        - name: FREESWITCH_DISABLE_NAT_DETECTION
          valueFrom:
            configMapKeyRef:
              name: freeswitch
              key: freeswitch.disable-nat-detection
        - name: FREESWITCH_TLS_ENABLE
          valueFrom:
            configMapKeyRef:
              name: freeswitch
              key: freeswitch.tls.enable
        ports:
        # - name: event-socket
        #   containerPort:  8021
        - name: mod-kazoo
          containerPort:  8031
        - name: sip
          protocol: UDP
          containerPort: 11000
        resources:
          requests:
            cpu: 8
            memory: 6Gi
          limits:
            cpu: 8
            memory: 6Gi
        readinessProbe:
          exec:
            command: ["fs_cli", "-x", "status", "|", "grep", "-q", "^UP"]
          initialDelaySeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          exec:
            command: ["fs_cli", "-x", "status", "|", "grep", "-q", "^UP"]
          initialDelaySeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        volumeMounts:
        - name: freeswitch-ramfs
          mountPath: /volumes/freeswitch
      volumes:
      - name: freeswitch-ramfs
        emptyDir:
          medium: Memory
      restartPolicy: Always
