apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: freeswitch
spec:
  template:
    metadata:
      name: freeswitch
      labels:
        app: freeswitch
        project: valuphone
        environment: production
    spec:
      nodeSelector: 
        kubernetes.io/hostname: adeno.valuphone.com
      hostNetwork: true
      volumes:
        - name: erlang-cookie-secret
          secret:
            secretName: erlang-cookie
      containers:
        - name: freeswitch
          image: callforamerica/freeswitch
          imagePullPolicy: Always
          volumeMounts:
            - name: erlang-cookie-secret
              readOnly: true
              mountPath: /etc/secrets/erlang
          env:
            - name: FREESWITCH_LOG_LEVEL
              value: info
          ports:
            - name: mod-kazoo
              protocol: TCP
              containerPort:  8031
            - name: sip
              protocol: UDP
              containerPort: 11000
          resources:
            requests:
              cpu: 4
              memory: 4G
            # limits:
            #   cpu: 
            #   memory: 
          readinessProbe:
            exec:
              command: ["fs_cli", "-x", "status", "|", "grep", "-q", "^UP"]
            initialDelaySeconds: 45
            timeoutSeconds: 15
          livenessProbe:
            exec:
              command: ["fs_cli", "-x", "status", "|", "grep", "-q", "^UP"]
            initialDelaySeconds: 45
            timeoutSeconds: 15
      restartPolicy: Always