kind: Service
apiVersion: v1
metadata: 
  name: freeswitch
spec:
  clusterIP: None
  selector:
    app: freeswitch
    project: valuphone
    environment: production
  ports:
    - name: mod-kazoo
      protocol: TCP
      containerPort:  8031
    - name: sip
      protocol: TCP
      port: 11000
