apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: freeswitch
spec:
  replicas: 2
  template:
    metadata:
      name: freeswitch
      labels:
        app: freeswitch
        kazoo-app: whistle_apps
        project: valuphone
        environment: production
    spec:
      hostNetwork: true
      volumes:
        - name: erlang-cookie-secret
          secret:
            secretName: erlang-cookie
      containers:
        - name: freeswitch
          image: callforamerica/freeswitch
          capabilities:
            add:
              - SYS_NICE
          env:
            - name: FREESWITCH_LOG_LEVEL
              value: info
            - name: FREESWITCH_DISABLE_NAT_DETECTION
              value: 'false'
          volumeMounts:
            - name: erlang-cookie-secret
              readOnly: true
              mountPath: /etc/secrets/erlang
          ports:
            - name: mod-kazoo
              protocol: TCP
              containerPort:  8031
            - name: sip
              protocol: UDP
              containerPort: 11000
          resources:
            requests: 
              cpu: 8
              memory: 8G
            # limits:
            #   cpu:
            #   memory:
          readinessProbe:
            exec:
              command: ["fs_cli", "-x", "status", "|", "grep", "-q", "^UP"]
            initialDelaySeconds: 10
            timeoutSeconds: 10
          livenessProbe:
            exec:
              command: ["fs_cli", "-x", "status", "|", "grep", "-q", "^UP"]
            initialDelaySeconds: 10
            timeoutSeconds: 10
          imagePullPolicy: Always
      restartPolicy: Always
