kind: Service
apiVersion: v1
metadata: 
  name: freeswitch
  labels:
    app: freeswitch
    role: sip-switch
    version: '1.6'
    environment: production
spec:
  selector:
    app: freeswitch
    project: valuphone
    version: '1.6'
    environment: production
  ports:
    - name: mod-kazoo
      protocol: TCP
      port: 8031
  clusterIP: None
