apiVersion: v1
kind: Service
metadata:
  name: freeswitch
  labels:
    app: freeswitch
    project: valuphone
    environment: production
spec:
  clusterIP: None
  selector:
    app: freeswitch
    project: valuphone
    environment: production
  ports:
  - name: event-socket
    port: 8021
  - name: mod-kazoo
    port: 8031
  - name: sip
    port: 11000
