kind: Pod
apiVersion: v1
metadata:
  name: freeswitch
  labels:
    app: freeswitch
    role: sip-switch
spec:
  volumes:
    - name: erlang-cookie-secret
      secret:
        secretName: erlang-cookie
  containers:
    - name: freeswitch
      image: callforamerica/freeswitch
      imagePullPolicy: Always
      volumeMounts:
        - name: erlang-cookie-secret
          readOnly: true
          mountPath: /etc/secrets/erlang
      ports:
        - name: mod-kazoo
          protocol: TCP
          containerPort: 8031
        - name: h-323-gatekeeper
          protocol: UDP
          containerPort: 1719
        - name: h-323-call-signaling
          protocol: TCP
          containerPort: 1720
        - name: stun-1
          protocol: UDP
          containerPort: 3478
        - name: stun-2
          protocol: UDP
          containerPort: 3479 
        - name: mlp-protocol-server
          protocol: TCP
          containerPort: 5002
        - name: neighborhood-service
          protocol: UDP
          containerPort: 5003
        - name: sip-uas-udp
          protocol: UDP
          containerPort: 5060
        - name: sip-uas-tcp
          protocol: TCP
          containerPort: 5060
        - name: sip-uas-nat-udp
          protocol: UDP
          containerPort: 5070
        - name: sip-uas-nat-tcp
          protocol: TCP
          containerPort: 5070
        - name: sip-uas-external-udp
          protocol: UDP
          containerPort: 5080
        - name: sip-uas-external-tcp
          protocol: TCP
          containerPort: 5080
        - name: esl
          protocol: TCP
          containerPort:  8021
        - name: webrtc-websocket-1
          protocol: TCP
          containerPort:  5066
        - name: webrtc-websocket-2
          protocol: TCP
          containerPort:  7443
    - name: epmd
      image: callforamerica/epmd
    - name: dns
      image: callforamerica/go-dnsmasq
  restartPolicy: Always