# create erlang cookie:  kubectl create secret generic erlang --from-literal=erlang.cookie=$(LC_ALL=C tr -cd '[:alnum:]' < /dev/urandom | head -c 64)
apiVersion: v1
kind: Secret
metadata:
  name: erlang
  labels:
    app: freeswitch
    test: 'true'
    environment: testing
type: Opaque
data:
  erlang.cookie: WlgyZVA4Umo4cnVmUjVJbjNnWGV1akhYNllseEREbnRyd3ZROE5kcGd3OXFOQjZ5UFhPUWhxNFF4bEc0WnZaQQ==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: freeswitch
  labels:
    app: freeswitch
    test: 'true'
    environment: testing
data:
  freeswitch.log.level: info
  freeswitch.log.color: 'true'
  freeswitch.rtp.port-range: '16384-32768'
  freeswitch.disable-nat-detection: 'false'
  freeswitch.tls.enable: 'false'
---
apiVersion: v1
kind: Service
metadata:
  name: freeswitch
  labels:
    app: freeswitch
    test: 'true'
    environment: testing
spec:
  clusterIP: None
  selector:
    app: freeswitch
  ports:
  # - name: event-socket
  #   port: 8021
  - name: mod-kazoo
    port: 8031
  - name: sip
    port: 11000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: freeswitch
  labels:
    app: freeswitch
    test: 'true'
    environment: testing
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: freeswitch
        test: 'true'
        environment: testing
    spec:
      hostNetwork: true
      containers:
      - name: freeswitch
        image: telephoneorg/freeswitch
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
            - NET_ADMIN
            - NET_RAW
            - NET_BROADCAST
            - SYS_NICE
            - SYS_RESOURCE
        env:
        - name: ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              name: erlang
              key: erlang.cookie
        - name: FREESWITCH_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: freeswitch
              key: freeswitch.log.level
        - name: FREESWITCH_LOG_COLOR
          valueFrom:
            configMapKeyRef:
              name: freeswitch
              key: freeswitch.log.color
        - name: FREESWITCH_RTP_PORT_RANGE
          valueFrom:
            configMapKeyRef:
              name: freeswitch
              key: freeswitch.rtp.port-range
        - name: FREESWITCH_DISABLE_NAT_DETECTION
          valueFrom:
            configMapKeyRef:
              name: freeswitch
              key: freeswitch.disable-nat-detection
        - name: FREESWITCH_TLS_ENABLE
          valueFrom:
            configMapKeyRef:
              name: freeswitch
              key: freeswitch.tls.enable
        ports:
        # - name: event-socket
        #   containerPort:  8021
        - name: mod-kazoo
          containerPort:  8031
        - name: sip
          protocol: UDP
          containerPort: 11000
        readinessProbe:
          exec:
            command: ["fs_cli", "-x", "status", "|", "grep", "-q", "^UP"]
          initialDelaySeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          exec:
            command: ["fs_cli", "-x", "status", "|", "grep", "-q", "^UP"]
          initialDelaySeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        volumeMounts:
        - name: freeswitch-ramfs
          mountPath: /volumes/freeswitch
      volumes:
      - name: freeswitch-ramfs
        emptyDir:
          medium: Memory
      restartPolicy: Always
      dnsPolicy: ClusterFirstWithHostNet
